import "./globals.css";
import { Montserrat, Poppins } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-montesrrat",
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Fitterify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${poppins.variable} ${montserrat.className}`}
      >
        {children}
      </body>
    </html>
  );
}
